### ISSUE TITLE
Trained Models 

### ISSUE THREAD

**Issue by vikashg** [DionGR/3d-segmentation-coronary-arteries-asoca#1]
Hi @DionGR 
Will it be possible for you to share the trained model ?

Thanks 
Vikash

**Comment by DionGR** [comment]
Hello @vikashg,

I will send you the weights of the optimal model by e-mail.

**Comment by vikashg** [comment]
Hi @DionGR, 
That will be awesome. Do you need my email ?
Vikash

**Comment by DionGR** [comment]
I sent it to the one I found on your website from your profile. If it's not up-to-date, let me know which e-mail you'd like for me to use.
